// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAyUJgrdrX8q5CW2I1c97QvJGcWQd2sk',
    appId: '1:969634057611:web:98398c99a66c30e526f38e',
    messagingSenderId: '969634057611',
    projectId: 'notes-55bcc',
    authDomain: 'notes-55bcc.firebaseapp.com',
    storageBucket: 'notes-55bcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ByTTsaw_agM-a9W6cByIbpusDlQR1ys',
    appId: '1:969634057611:android:bf99da080f17c45a26f38e',
    messagingSenderId: '969634057611',
    projectId: 'notes-55bcc',
    storageBucket: 'notes-55bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EFyd5DlI-dSsUtmk0DL9FwPHwsd728k',
    appId: '1:969634057611:ios:20e5c6352b68c8bf26f38e',
    messagingSenderId: '969634057611',
    projectId: 'notes-55bcc',
    storageBucket: 'notes-55bcc.firebasestorage.app',
    iosBundleId: 'com.example.flNote1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuAyUJgrdrX8q5CW2I1c97QvJGcWQd2sk',
    appId: '1:969634057611:web:6ca83c7bf927bb8626f38e',
    messagingSenderId: '969634057611',
    projectId: 'notes-55bcc',
    authDomain: 'notes-55bcc.firebaseapp.com',
    storageBucket: 'notes-55bcc.firebasestorage.app',
  );
}
